### ISSUE TITLE
Главное меню - дизайн кнопок

### ISSUE THREAD

**Issue by MrKarrol** [hackatomsk2017-2048/black-hole-client#17]
Кнопка "Зарегистрироваться"
Кнопка "Войти"
Кнопка "Играть"
(все три кнопки выше - это одна кнопка, у которой просто меняется обложка)
Кнопка "Личный кабинет" (+заблокированный вариант)
Кнопка "Таблица рекордов" (+заблокированный вариант)
Кнопка "Правила игры"

**Comment by talgo90** [comment]
кнопки одни и те же https://drive.google.com/drive/folders/1ZLbkkxqSn_wZSmU4kPHrrdQxeGS2JpQs

**Comment by talgo90** [comment]
https://drive.google.com/drive/folders/1XT3NCfy_4kN1CiZqr5N1ib5dTJ8e_rvu 
кнопки играть вход зарегистрироваться смежные, открываются в зависимости статуса игрока

**Comment by talgo90** [comment]
https://drive.google.com/drive/folders/1eG1FyRd3m0TXrsd8k8qHiGRgOzJ5P_l6 изменилась ссылка
