### ISSUE TITLE
Форма регистрации - расположение элементов, дизайн

### ISSUE THREAD

**Issue by MrKarrol** [hackatomsk2017-2048/black-hole-client#20]
Логин, пароль, текстовые поля

**Comment by MrKarrol** [comment]
Дополнение - появление кнопок "Регистрация" и "Вход" снизу формы. По стилю отличаются от кнопки "Зарегистрироваться".

**Comment by MrKarrol** [comment]
Поля в форме:
1. Никнейм.
2. E-mail.
3. Пароль.
4. Пароль ещё раз.

**Comment by talgo90** [comment]
https://drive.google.com/open?id=1XBGhwvTU5py2uBxbcCDj8uZXY58E9xK-
