### ISSUE TITLE
Дизайн фона главного меню

### ISSUE THREAD

**Issue by MrKarrol** [hackatomsk2017-2048/black-hole-client#26]

**Comment by talgo90** [comment]
https://drive.google.com/drive/folders/1s_hAppWrBZxk2iObnyvXsVWedfUdIpM0

**Comment by talgo90** [comment]
https://drive.google.com/drive/folders/1s_hAppWrBZxk2iObnyvXsVWedfUdIpM0
изменила немного дизайн
