### ISSUE TITLE
Форма ожидания противника

### ISSUE THREAD

**Issue by MrKarrol** [hackatomsk2017-2048/black-hole-client#31]

**Comment by MrKarrol** [comment]
После выбора ставки и клика на кнопку "Найти противника"

**Comment by PolinaEfimova** [comment]
https://yadi.sk/d/nCD0bXpv3Pp3Ky

**Comment by MrKarrol** [comment]
Смена структуры формы

**Comment by talgo90** [comment]
https://drive.google.com/drive/folders/1gCylU5xZ_qgtZ2rdspgBmQO0riaJr1O1 КОСМОЛЕЕЕЕЕЕТ УХУУУУ!!!
