### ISSUE TITLE
Переработать кнопку Зарегистрироваться в Главном меню

### ISSUE THREAD

**Issue by MrKarrol** [hackatomsk2017-2048/black-hole-client#36]
Вместо кнопки Зарегистрироваться будет Зарегистрироваться/Войти. Это связано с тем, что после регистрации игроку в этой форме отпадёт необходимость, а место для Войти выделено не было (было определено на место Зарегистрироваться, но это неверно, потому что приложением с того же устройства может воспользоваться другой игрок).

**Comment by talgo90** [comment]
https://drive.google.com/drive/folders/1eG1FyRd3m0TXrsd8k8qHiGRgOzJ5P_l6
