### ISSUE TITLE
Дизайн подготовительного экрана - координаты элементов и размеры экрана в пикселях

### ISSUE THREAD

**Issue by MrKarrol** [hackatomsk2017-2048/black-hole-client#49]

**Comment by MrKarrol** [comment]
Дожидаюсь дизайнера, чтобы сделать схему на уровне

**Comment by MrKarrol** [comment]
Масштаб экрана, соотношение сторон, центры элементов, их радиусы и ширина/высота некруглых объектов, расстояние от одного до другого (от одного центра до другого), основные ориентиры. Единица измерения - единица масштаба, минимально максимальная величина между двумя элементами, при этом удобная для подсчёта. Пример в тетради.

**Comment by talgo90** [comment]
https://drive.google.com/drive/folders/1z6Nmtzd2Ln0-CyzKrbY9MOkwr8ulLr_B
